### ISSUE TITLE
doesn't works again

### ISSUE THREAD

**Issue by victorhck** [arlogn/easyshare#16]
Hello!
Since a couple of days, your (great) plugin doesn't works again.
Yesterday I get a 406 error, when I post something. Today is stuck and nothing happens... :(

It's something wrong in my Firefox?

Thanks in advance.

**Comment by arlogn** [comment]
Nope, your firefox is ok. Most probably the problem is the csrf token. The addon gets a new token only with 401. I'll try to fix it tonight.
In the meantime you can try this:

1. disable the addon and close diaspora
2. remove the diaspora cookie: Preferences/Privacy/Remove Individual Cookies search your pod and remove `remember_user_token`
3. delete this file in your home: `/.mozilla/firefox/<YOUR-PROFILE>/jetpack/jid1-gqfeTXcouyVkpg@jetpack/simple-storage/store.json`
4. enable the addon

Maybe this help.

**Comment by victorhck** [comment]
Thanks again for your work and code!!
And thanks for the tip. But today all seems to works fine ¿?

**Comment by arlogn** [comment]
Yes, I already knew the problem with the display of the provider. I made a small mistake the last time and I realized only after sending the update. Tomorrow I send the new update that should fix everything. Or at least I hope.  :smile:

**Comment by victorhck** [comment]
Great new festures with this new version!! :)
Thanks a lot!!
